apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: pizza-notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: pizza-shop-config
            - secretRef:
                name: pizza-shop-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 5
            periodSeconds: 5
